baseURL = "https://smetal1.github.io/thunder-db-docs/"
title = "ThunderDB Documentation"
languageCode = "en-us"
contentDir = "content"
enableRobotsTXT = true
enableGitInfo = false

# theme = ["docsy"]  # Using Hugo modules instead

[module]
  proxy = "direct"
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "ThunderDB â€” The Distributed HTAP Database for the AI Era"
copyright = "ThunderDB Contributors"
privacy_policy = ""

offlineSearch = true
prism_syntax_highlighting = false

version_menu = "Releases"
archived_version = false
version = "0.1.0"
url_latest_version = "https://thunderdb.io/docs"

github_repo = "https://github.com/smetal1/thunder-db"
github_project_repo = "https://github.com/smetal1/thunder-db"
github_branch = "main"

[params.ui]
breadcrumb_disable = false
sidebar_menu_compact = true
sidebar_menu_foldable = true
sidebar_search_disable = false
navbar_logo = true
footer_about_enable = true
sidebar_cache_limit = 10

[params.ui.feedback]
enable = true
yes = 'Glad to hear it! <a href="https://github.com/smetal1/thunder-db/issues/new">Tell us how we can improve</a>.'
no = 'Sorry to hear that. <a href="https://github.com/smetal1/thunder-db/issues/new">Tell us how we can improve</a>.'

[params.links]
[[params.links.developer]]
name = "GitHub"
url = "https://github.com/smetal1/thunder-db"
icon = "fab fa-github"
desc = "Source code and development"
[[params.links.developer]]
name = "Discussions"
url = "https://github.com/smetal1/thunder-db/discussions"
icon = "fas fa-comments"
desc = "Community discussions"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser.attribute]
block = true
[markup.highlight]
style = "dracula"
lineNos = false
guessSyntax = true

[menu]
[[menu.main]]
name = "Documentation"
weight = 10
url = "/"
[[menu.main]]
name = "Architecture"
weight = 20
url = "/docs/architecture/"
[[menu.main]]
name = "API Reference"
weight = 30
url = "/docs/developer/api-reference/"
[[menu.main]]
name = "GitHub"
weight = 50
url = "https://github.com/smetal1/thunder-db"
pre = "<i class='fab fa-github'></i>"

[outputs]
home = ["HTML"]
section = ["HTML"]

[mediaTypes]
[mediaTypes."application/javascript"]
suffixes = ["js"]

[security]
[security.funcs]
getenv = ["^HUGO_", "^CI$"]
